apiVersion: apps/v1
kind: Deployment
metadata:
  name: threat-detection-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: threat-api
  template:
    metadata:
      labels:
        app: threat-api
    spec:
      containers:
      - name: api
        image: your-dockerhub/threat-detection-api:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: threat-api-service
spec:
  type: LoadBalancer
  selector:
    app: threat-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000